/* tslint:disable */
/* eslint-disable */
/**
 * Todo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Def0
 */
export interface Def0 {
    /**
     * 
     * @type {string}
     * @memberof Def0
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Def0
     */
    'description': string;
    /**
     * 
     * @type {Array<Def1>}
     * @memberof Def0
     */
    'todos': Array<Def1>;
}
/**
 * 
 * @export
 * @interface Def1
 */
export interface Def1 {
    /**
     * 
     * @type {string}
     * @memberof Def1
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Def1
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof Def1
     */
    'state': Def1StateEnum;
}

export const Def1StateEnum = {
    Pending: 'pending',
    InProgress: 'in-progress',
    Done: 'done'
} as const;

export type Def1StateEnum = typeof Def1StateEnum[keyof typeof Def1StateEnum];

/**
 * Toutes les listes récupérées
 * @export
 * @interface ListsGet200Response
 */
export interface ListsGet200Response {
    /**
     * 
     * @type {Array<Def0>}
     * @memberof ListsGet200Response
     */
    'data'?: Array<Def0>;
}
/**
 * Item ajouté
 * @export
 * @interface ListsIdItemsPost201Response
 */
export interface ListsIdItemsPost201Response {
    /**
     * 
     * @type {Def0}
     * @memberof ListsIdItemsPost201Response
     */
    'data'?: Def0;
}
/**
 * Liste mise à jour
 * @export
 * @interface ListsIdPut200Response
 */
export interface ListsIdPut200Response {
    /**
     * 
     * @type {string}
     * @memberof ListsIdPut200Response
     */
    'message'?: string;
    /**
     * 
     * @type {Def0}
     * @memberof ListsIdPut200Response
     */
    'data'?: Def0;
}
/**
 * Item supprimé
 * @export
 * @interface ListsListIdItemsItemIdDelete200Response
 */
export interface ListsListIdItemsItemIdDelete200Response {
    /**
     * 
     * @type {string}
     * @memberof ListsListIdItemsItemIdDelete200Response
     */
    'message'?: string;
    /**
     * 
     * @type {Def0}
     * @memberof ListsListIdItemsItemIdDelete200Response
     */
    'data'?: Def0;
}
/**
 * Item mis à jour
 * @export
 * @interface ListsListIdItemsItemIdPut200Response
 */
export interface ListsListIdItemsItemIdPut200Response {
    /**
     * 
     * @type {string}
     * @memberof ListsListIdItemsItemIdPut200Response
     */
    'message'?: string;
    /**
     * 
     * @type {Def0}
     * @memberof ListsListIdItemsItemIdPut200Response
     */
    'data'?: Def0;
}
/**
 * Nouvelle liste créée
 * @export
 * @interface ListsPost201Response
 */
export interface ListsPost201Response {
    /**
     * 
     * @type {Def0}
     * @memberof ListsPost201Response
     */
    'data'?: Def0;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rootGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rootGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.rootGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.rootGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public rootGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).rootGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ItemsApi - axios parameter creator
 * @export
 */
export const ItemsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Ajouter un item à une liste de tâches
         * @param {string} id 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsIdItemsPost: async (id: string, def1?: Def1, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listsIdItemsPost', 'id', id)
            const localVarPath = `/lists/{id}/items`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(def1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Supprime un item d’une liste
         * @param {string} listId 
         * @param {string} itemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsListIdItemsItemIdDelete: async (listId: string, itemId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listId' is not null or undefined
            assertParamExists('listsListIdItemsItemIdDelete', 'listId', listId)
            // verify required parameter 'itemId' is not null or undefined
            assertParamExists('listsListIdItemsItemIdDelete', 'itemId', itemId)
            const localVarPath = `/lists/{listId}/items/{itemId}`
                .replace(`{${"listId"}}`, encodeURIComponent(String(listId)))
                .replace(`{${"itemId"}}`, encodeURIComponent(String(itemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Mettre à jour un item dans une liste de tâches
         * @param {string} listId 
         * @param {string} itemId 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsListIdItemsItemIdPut: async (listId: string, itemId: string, def1?: Def1, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listId' is not null or undefined
            assertParamExists('listsListIdItemsItemIdPut', 'listId', listId)
            // verify required parameter 'itemId' is not null or undefined
            assertParamExists('listsListIdItemsItemIdPut', 'itemId', itemId)
            const localVarPath = `/lists/{listId}/items/{itemId}`
                .replace(`{${"listId"}}`, encodeURIComponent(String(listId)))
                .replace(`{${"itemId"}}`, encodeURIComponent(String(itemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(def1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ItemsApi - functional programming interface
 * @export
 */
export const ItemsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ItemsApiAxiosParamCreator(configuration)
    return {
        /**
         * Ajouter un item à une liste de tâches
         * @param {string} id 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listsIdItemsPost(id: string, def1?: Def1, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListsIdItemsPost201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listsIdItemsPost(id, def1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ItemsApi.listsIdItemsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Supprime un item d’une liste
         * @param {string} listId 
         * @param {string} itemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listsListIdItemsItemIdDelete(listId: string, itemId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListsListIdItemsItemIdDelete200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listsListIdItemsItemIdDelete(listId, itemId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ItemsApi.listsListIdItemsItemIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Mettre à jour un item dans une liste de tâches
         * @param {string} listId 
         * @param {string} itemId 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listsListIdItemsItemIdPut(listId: string, itemId: string, def1?: Def1, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListsListIdItemsItemIdPut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listsListIdItemsItemIdPut(listId, itemId, def1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ItemsApi.listsListIdItemsItemIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ItemsApi - factory interface
 * @export
 */
export const ItemsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ItemsApiFp(configuration)
    return {
        /**
         * Ajouter un item à une liste de tâches
         * @param {string} id 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsIdItemsPost(id: string, def1?: Def1, options?: RawAxiosRequestConfig): AxiosPromise<ListsIdItemsPost201Response> {
            return localVarFp.listsIdItemsPost(id, def1, options).then((request) => request(axios, basePath));
        },
        /**
         * Supprime un item d’une liste
         * @param {string} listId 
         * @param {string} itemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsListIdItemsItemIdDelete(listId: string, itemId: string, options?: RawAxiosRequestConfig): AxiosPromise<ListsListIdItemsItemIdDelete200Response> {
            return localVarFp.listsListIdItemsItemIdDelete(listId, itemId, options).then((request) => request(axios, basePath));
        },
        /**
         * Mettre à jour un item dans une liste de tâches
         * @param {string} listId 
         * @param {string} itemId 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsListIdItemsItemIdPut(listId: string, itemId: string, def1?: Def1, options?: RawAxiosRequestConfig): AxiosPromise<ListsListIdItemsItemIdPut200Response> {
            return localVarFp.listsListIdItemsItemIdPut(listId, itemId, def1, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ItemsApi - object-oriented interface
 * @export
 * @class ItemsApi
 * @extends {BaseAPI}
 */
export class ItemsApi extends BaseAPI {
    /**
     * Ajouter un item à une liste de tâches
     * @param {string} id 
     * @param {Def1} [def1] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ItemsApi
     */
    public listsIdItemsPost(id: string, def1?: Def1, options?: RawAxiosRequestConfig) {
        return ItemsApiFp(this.configuration).listsIdItemsPost(id, def1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Supprime un item d’une liste
     * @param {string} listId 
     * @param {string} itemId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ItemsApi
     */
    public listsListIdItemsItemIdDelete(listId: string, itemId: string, options?: RawAxiosRequestConfig) {
        return ItemsApiFp(this.configuration).listsListIdItemsItemIdDelete(listId, itemId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Mettre à jour un item dans une liste de tâches
     * @param {string} listId 
     * @param {string} itemId 
     * @param {Def1} [def1] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ItemsApi
     */
    public listsListIdItemsItemIdPut(listId: string, itemId: string, def1?: Def1, options?: RawAxiosRequestConfig) {
        return ItemsApiFp(this.configuration).listsListIdItemsItemIdPut(listId, itemId, def1, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ListsApi - axios parameter creator
 * @export
 */
export const ListsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Récupère toutes les listes de tâches
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/lists/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Ajouter un item à une liste de tâches
         * @param {string} id 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsIdItemsPost: async (id: string, def1?: Def1, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listsIdItemsPost', 'id', id)
            const localVarPath = `/lists/{id}/items`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(def1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Mettre à jour une liste existante
         * @param {string} id 
         * @param {Def0} [def0] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsIdPut: async (id: string, def0?: Def0, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listsIdPut', 'id', id)
            const localVarPath = `/lists/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(def0, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Supprime un item d’une liste
         * @param {string} listId 
         * @param {string} itemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsListIdItemsItemIdDelete: async (listId: string, itemId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listId' is not null or undefined
            assertParamExists('listsListIdItemsItemIdDelete', 'listId', listId)
            // verify required parameter 'itemId' is not null or undefined
            assertParamExists('listsListIdItemsItemIdDelete', 'itemId', itemId)
            const localVarPath = `/lists/{listId}/items/{itemId}`
                .replace(`{${"listId"}}`, encodeURIComponent(String(listId)))
                .replace(`{${"itemId"}}`, encodeURIComponent(String(itemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Mettre à jour un item dans une liste de tâches
         * @param {string} listId 
         * @param {string} itemId 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsListIdItemsItemIdPut: async (listId: string, itemId: string, def1?: Def1, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listId' is not null or undefined
            assertParamExists('listsListIdItemsItemIdPut', 'listId', listId)
            // verify required parameter 'itemId' is not null or undefined
            assertParamExists('listsListIdItemsItemIdPut', 'itemId', itemId)
            const localVarPath = `/lists/{listId}/items/{itemId}`
                .replace(`{${"listId"}}`, encodeURIComponent(String(listId)))
                .replace(`{${"itemId"}}`, encodeURIComponent(String(itemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(def1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Crée une nouvelle liste de tâches
         * @param {Def0} [def0] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsPost: async (def0?: Def0, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/lists/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(def0, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ListsApi - functional programming interface
 * @export
 */
export const ListsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ListsApiAxiosParamCreator(configuration)
    return {
        /**
         * Récupère toutes les listes de tâches
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListsApi.listsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Ajouter un item à une liste de tâches
         * @param {string} id 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listsIdItemsPost(id: string, def1?: Def1, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListsIdItemsPost201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listsIdItemsPost(id, def1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListsApi.listsIdItemsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Mettre à jour une liste existante
         * @param {string} id 
         * @param {Def0} [def0] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listsIdPut(id: string, def0?: Def0, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListsIdPut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listsIdPut(id, def0, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListsApi.listsIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Supprime un item d’une liste
         * @param {string} listId 
         * @param {string} itemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listsListIdItemsItemIdDelete(listId: string, itemId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListsListIdItemsItemIdDelete200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listsListIdItemsItemIdDelete(listId, itemId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListsApi.listsListIdItemsItemIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Mettre à jour un item dans une liste de tâches
         * @param {string} listId 
         * @param {string} itemId 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listsListIdItemsItemIdPut(listId: string, itemId: string, def1?: Def1, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListsListIdItemsItemIdPut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listsListIdItemsItemIdPut(listId, itemId, def1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListsApi.listsListIdItemsItemIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Crée une nouvelle liste de tâches
         * @param {Def0} [def0] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listsPost(def0?: Def0, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListsPost201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listsPost(def0, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListsApi.listsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ListsApi - factory interface
 * @export
 */
export const ListsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ListsApiFp(configuration)
    return {
        /**
         * Récupère toutes les listes de tâches
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsGet(options?: RawAxiosRequestConfig): AxiosPromise<ListsGet200Response> {
            return localVarFp.listsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Ajouter un item à une liste de tâches
         * @param {string} id 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsIdItemsPost(id: string, def1?: Def1, options?: RawAxiosRequestConfig): AxiosPromise<ListsIdItemsPost201Response> {
            return localVarFp.listsIdItemsPost(id, def1, options).then((request) => request(axios, basePath));
        },
        /**
         * Mettre à jour une liste existante
         * @param {string} id 
         * @param {Def0} [def0] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsIdPut(id: string, def0?: Def0, options?: RawAxiosRequestConfig): AxiosPromise<ListsIdPut200Response> {
            return localVarFp.listsIdPut(id, def0, options).then((request) => request(axios, basePath));
        },
        /**
         * Supprime un item d’une liste
         * @param {string} listId 
         * @param {string} itemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsListIdItemsItemIdDelete(listId: string, itemId: string, options?: RawAxiosRequestConfig): AxiosPromise<ListsListIdItemsItemIdDelete200Response> {
            return localVarFp.listsListIdItemsItemIdDelete(listId, itemId, options).then((request) => request(axios, basePath));
        },
        /**
         * Mettre à jour un item dans une liste de tâches
         * @param {string} listId 
         * @param {string} itemId 
         * @param {Def1} [def1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsListIdItemsItemIdPut(listId: string, itemId: string, def1?: Def1, options?: RawAxiosRequestConfig): AxiosPromise<ListsListIdItemsItemIdPut200Response> {
            return localVarFp.listsListIdItemsItemIdPut(listId, itemId, def1, options).then((request) => request(axios, basePath));
        },
        /**
         * Crée une nouvelle liste de tâches
         * @param {Def0} [def0] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsPost(def0?: Def0, options?: RawAxiosRequestConfig): AxiosPromise<ListsPost201Response> {
            return localVarFp.listsPost(def0, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ListsApi - object-oriented interface
 * @export
 * @class ListsApi
 * @extends {BaseAPI}
 */
export class ListsApi extends BaseAPI {
    /**
     * Récupère toutes les listes de tâches
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public listsGet(options?: RawAxiosRequestConfig) {
        return ListsApiFp(this.configuration).listsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Ajouter un item à une liste de tâches
     * @param {string} id 
     * @param {Def1} [def1] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public listsIdItemsPost(id: string, def1?: Def1, options?: RawAxiosRequestConfig) {
        return ListsApiFp(this.configuration).listsIdItemsPost(id, def1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Mettre à jour une liste existante
     * @param {string} id 
     * @param {Def0} [def0] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public listsIdPut(id: string, def0?: Def0, options?: RawAxiosRequestConfig) {
        return ListsApiFp(this.configuration).listsIdPut(id, def0, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Supprime un item d’une liste
     * @param {string} listId 
     * @param {string} itemId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public listsListIdItemsItemIdDelete(listId: string, itemId: string, options?: RawAxiosRequestConfig) {
        return ListsApiFp(this.configuration).listsListIdItemsItemIdDelete(listId, itemId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Mettre à jour un item dans une liste de tâches
     * @param {string} listId 
     * @param {string} itemId 
     * @param {Def1} [def1] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public listsListIdItemsItemIdPut(listId: string, itemId: string, def1?: Def1, options?: RawAxiosRequestConfig) {
        return ListsApiFp(this.configuration).listsListIdItemsItemIdPut(listId, itemId, def1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Crée une nouvelle liste de tâches
     * @param {Def0} [def0] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public listsPost(def0?: Def0, options?: RawAxiosRequestConfig) {
        return ListsApiFp(this.configuration).listsPost(def0, options).then((request) => request(this.axios, this.basePath));
    }
}



